/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreKivoRouteImport } from './routes/sobre-kivo'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CoberturasRouteImport } from './routes/coberturas'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegurosRcRouteImport } from './routes/seguros.rc'
import { Route as SegurosPremiumRouteImport } from './routes/seguros.premium'
import { Route as SegurosCarePlusRouteImport } from './routes/seguros.care-plus'
import { Route as SegurosCareRouteImport } from './routes/seguros.care'

const SobreKivoRoute = SobreKivoRouteImport.update({
  id: '/sobre-kivo',
  path: '/sobre-kivo',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturasRoute = CoberturasRouteImport.update({
  id: '/coberturas',
  path: '/coberturas',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosRcRoute = SegurosRcRouteImport.update({
  id: '/seguros/rc',
  path: '/seguros/rc',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosPremiumRoute = SegurosPremiumRouteImport.update({
  id: '/seguros/premium',
  path: '/seguros/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosCarePlusRoute = SegurosCarePlusRouteImport.update({
  id: '/seguros/care-plus',
  path: '/seguros/care-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosCareRoute = SegurosCareRouteImport.update({
  id: '/seguros/care',
  path: '/seguros/care',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/coberturas': typeof CoberturasRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/faq': typeof FaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-kivo': typeof SobreKivoRoute
  '/seguros/care': typeof SegurosCareRoute
  '/seguros/care-plus': typeof SegurosCarePlusRoute
  '/seguros/premium': typeof SegurosPremiumRoute
  '/seguros/rc': typeof SegurosRcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/coberturas': typeof CoberturasRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/faq': typeof FaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-kivo': typeof SobreKivoRoute
  '/seguros/care': typeof SegurosCareRoute
  '/seguros/care-plus': typeof SegurosCarePlusRoute
  '/seguros/premium': typeof SegurosPremiumRoute
  '/seguros/rc': typeof SegurosRcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/coberturas': typeof CoberturasRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/faq': typeof FaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-kivo': typeof SobreKivoRoute
  '/seguros/care': typeof SegurosCareRoute
  '/seguros/care-plus': typeof SegurosCarePlusRoute
  '/seguros/premium': typeof SegurosPremiumRoute
  '/seguros/rc': typeof SegurosRcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/coberturas'
    | '/como-funciona'
    | '/faq'
    | '/sitemap.xml'
    | '/sobre-kivo'
    | '/seguros/care'
    | '/seguros/care-plus'
    | '/seguros/premium'
    | '/seguros/rc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/coberturas'
    | '/como-funciona'
    | '/faq'
    | '/sitemap.xml'
    | '/sobre-kivo'
    | '/seguros/care'
    | '/seguros/care-plus'
    | '/seguros/premium'
    | '/seguros/rc'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/coberturas'
    | '/como-funciona'
    | '/faq'
    | '/sitemap.xml'
    | '/sobre-kivo'
    | '/seguros/care'
    | '/seguros/care-plus'
    | '/seguros/premium'
    | '/seguros/rc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CoberturasRoute: typeof CoberturasRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  FaqRoute: typeof FaqRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreKivoRoute: typeof SobreKivoRoute
  SegurosCareRoute: typeof SegurosCareRoute
  SegurosCarePlusRoute: typeof SegurosCarePlusRoute
  SegurosPremiumRoute: typeof SegurosPremiumRoute
  SegurosRcRoute: typeof SegurosRcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-kivo': {
      id: '/sobre-kivo'
      path: '/sobre-kivo'
      fullPath: '/sobre-kivo'
      preLoaderRoute: typeof SobreKivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coberturas': {
      id: '/coberturas'
      path: '/coberturas'
      fullPath: '/coberturas'
      preLoaderRoute: typeof CoberturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros/rc': {
      id: '/seguros/rc'
      path: '/seguros/rc'
      fullPath: '/seguros/rc'
      preLoaderRoute: typeof SegurosRcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros/premium': {
      id: '/seguros/premium'
      path: '/seguros/premium'
      fullPath: '/seguros/premium'
      preLoaderRoute: typeof SegurosPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros/care-plus': {
      id: '/seguros/care-plus'
      path: '/seguros/care-plus'
      fullPath: '/seguros/care-plus'
      preLoaderRoute: typeof SegurosCarePlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros/care': {
      id: '/seguros/care'
      path: '/seguros/care'
      fullPath: '/seguros/care'
      preLoaderRoute: typeof SegurosCareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CoberturasRoute: CoberturasRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  FaqRoute: FaqRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreKivoRoute: SobreKivoRoute,
  SegurosCareRoute: SegurosCareRoute,
  SegurosCarePlusRoute: SegurosCarePlusRoute,
  SegurosPremiumRoute: SegurosPremiumRoute,
  SegurosRcRoute: SegurosRcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
